<pre class='metadata'>
Title: Data Footprints
Shortname: footprints
Level: 1
Status: w3c/ED
Group: Solid Community Group
URL: https://solid.github.io/specification/footprints/
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract:
  This document introduces a description model
  to decide where new resources are stored
  and how they are wired up.
</pre>

<pre class=include>path: introduction.bs</pre>
