<pre class='metadata'>
Title: WebID-TLS
Shortname: webid-tls
Level: 1
Status: w3c/ED
Group: Solid Community Group
URL: https://solid.github.io/specification/webid-tls/
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract:
  This document introduces a mechanism for authenticating agents with a WebID
  through the OpenID Connect protocol.
</pre>

<pre class=include>path: introduction.bs</pre>
