<pre class='metadata'>
Title: Web Access Control
Shortname: wac
Level: 1
Status: w3c/ED
Group: Solid Community Group
URL: https://solid.github.io/specification/
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract:
  This document introduces a mechanism
  for fine-grained access control to resources on the Web.
</pre>

<pre class=include>path: introduction.bs</pre>
